# 服务运行端口
port: :3000 

# 日志存储位置
log: ./log/

# 需要执行 hooks 的列表
list:
  - static # 服务名 (随便设置, 下方的详细配置要和这里一致)
  - home # 第二个服务, 假如下方未配置, secret、url、cmd 默认与服务名一致

# 配置 hooks
home:
  secret: fzf404  # WebHooks 密钥
  url: /vue    # WebHooks URL
  cmd: ./shell/vue.sh  # 执行 shell 的文件名

# 邮件服务
mail:
  enable: false # 是否开启
  host: smtp.gmail.com # smtp 地址
  port: 25 # smtp 端口
  user: account@gmail.com # 发送方邮箱
  pass: 123abc # 发送方密码
  to: # 接收邮件的用户
    - user1@example.com
    - user2@example.com