# 服务运行端口
port: :3000 

# 日志存储位置
log: ./log/

# 需要执行 hooks 的列表
list:
  - demo # 服务名 (随便设置, 下方的详细配置要和这里一致)
  - test # 第二个服务, 假如下方未配置, secret、url、cmd 默认与服务名一致

# 配置 hooks
demo:
  secret: fzf404  # WebHooks 密钥
  url: /demo    # WebHooks URL
  cmd: ./shell/demo.sh  # 执行shell的文件名

# 邮件服务
mail:
  enable: false
  host: smtp.gmail.com
  port: 25
  user: account@gmail.com
  pass: 123abc
  to:
    - user1@example.com
    - user2@example.com