port: 3000  # 端口

list:
  - blog
  - note
  - home
  - tabox
  - fzf

blog:
  secret: blog  # WebHooks 密钥
  url: /blog    # WebHooks URL
  cmd: ./shell/blog.sh  # 执行文件名

# note: 
  # secret、url、cmd与name一样时，只需在list中配置
