# 端口
port: :3000 

# 日志信息位置
log: ./log/

# 需要执行的列表
# name、secret、url与cmd一样时，只需在list中配置
list:
  - note
  - home
  - demo

# 自定义示例
demo:
  secret: fzf404  # WebHooks 密钥
  url: /demo    # WebHooks URL
  cmd: ./shell/demo.sh  # 执行文件名
