list:
  - blog
  - note
  - home
  - tabox

blog:
  secret: blog # WebHooks 密钥
  url: /blog # WebHooks URL
  cmd: ./shell/blog.sh # 执行文件名

note:
  secret: note # WebHooks 密钥

home:
  secret: home # WebHooks 密钥

tabox:
  secret: tabox # WebHooks 密钥
